binary_sensor:
  - platform: workday
    country: DE

  - platform: trend
    sensors:
      # Tracks 3 humidity readings over 10 minutes. If the change is greater than 10%, evals to true. (10/(60*10))
      presence_bathroom_shower_on:
        max_samples: 3
        entity_id: sensor.bathroom_humidity
        sample_duration: 600
        min_gradient: 0.01666
        # Tracks 2 humidity readings over 5 minutes. If the change decrease is greater than 5%, evals to true. (-5/(60*5))
        # Bumped samples down from 4 to 2, because it was staying on way too long.
      presence_bathroom_shower_off:
        max_samples: 2
        entity_id: sensor.bathroom_humidity
        sample_duration: 300
        min_gradient: -0.016666

  - platform: bayesian
    sensors:
      living_room_presence_bayesian:
        name: "Living Room Presence Bayesian"
        probability_threshold: 0.9
        observations:
          - entity_id: input_boolean.presence_living_room_motion
            prob_given_true: 0.7
            prob_given_false: 0.4
            platform: state
            to_state: "on"
          - entity_id: input_boolean.presence_living_room_switch
            prob_given_true: 1.0
            prob_given_false: 0.1
            platform: state
            to_state: "on"
          - entity_id: input_boolean.presence_living_room_tv
            prob_given_true: 0.9
            prob_given_false: 0.2
            platform: state
            to_state: "on"
          - entity_id: input_boolean.presence_living_room_brunos_pc
            prob_given_true: 0.9
            prob_given_false: 0.4
            platform: state
            to_state: "on"
          - entity_id: input_boolean.presence_living_room_assistant
            prob_given_true: 0.7
            prob_given_false: 0.6
            platform: state
            to_state: "on"

  - platform: template
    sensors:
      hallway_combined_sensor_motion:
        friendly_name: Motion Sensor Hallway Combined
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.hallway_kitchen_sensor_motion', 'on') or is_state('binary_sensor.hallway_sensor_motion', 'on') }}

      balcony_combined_sensor_door:
        friendly_name: Door Sensor Balcony Combined
        device_class: occupancy
        value_template: >-
          {{ is_state('binary_sensor.balcony_door_2_sensor', 'on') or is_state('binary_sensor.balcony_door_sensor', 'on') }}

      presence_bruno:
        friendly_name: "Presence Bruno"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_bruno', 'on') }}
      presence_sarah:
        friendly_name: "Presence Sarah"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_sarah', 'on') }}
      presence_someone:
        friendly_name: "Presence Someone"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.presence_someone', 'on') }}
      someone_home:
        device_class: presence
        friendly_name: Someone is home
        value_template: >-
          {{ is_state('group.presence', 'on') }}

      presence_living_room:
        friendly_name: Presence Living Room
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_living_room', 'on') }}
        entity_id:
          - input_boolean.presence_living_room_motion
          - input_boolean.presence_living_room_switch
          - input_boolean.presence_living_room_tv
          - input_boolean.presence_living_room_brunos_pc
          - input_boolean.presence_living_room_assistant
          - group.presence_living_room
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_living_room.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_dining_room:
        friendly_name: Presence Dining Room
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_dining_room', 'on') }}
        entity_id:
          - input_boolean.presence_dining_room_motion
          - input_boolean.presence_dining_room_switch
          - input_boolean.presence_dining_room_assistant
          - group.presence_dining_room
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_dining_room.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}

      presence_master_bedroom:
        friendly_name: Presence Master Bedroom
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_master_bedroom', 'on') }}
        entity_id:
          - input_boolean.presence_master_bedroom_motion
          - input_boolean.presence_master_bedroom_switch
          - input_boolean.presence_master_bedroom_sleeping
          - input_boolean.presence_master_bedroom_assistant
          - group.presence_master_bedroom
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_master_bedroom.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_emmas_bedroom:
        friendly_name: Presence Emma's Bedroom
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_emmas_bedroom', 'on') }}
        entity_id:
          - input_boolean.presence_emmas_bedroom_motion
          - input_boolean.presence_emmas_bedroom_switch
          - input_boolean.presence_emmas_bedroom_sleeping
          - input_boolean.presence_emmas_bedroom_assistant
          - group.presence_emmas_bedroom
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_emmas_bedroom.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_kitchen:
        friendly_name: Presence Kitchen
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_kitchen', 'on') }}
        entity_id:
          - input_boolean.presence_kitchen_motion
          - input_boolean.presence_kitchen_assistant
          - group.presence_kitchen
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_kitchen.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_hallway:
        friendly_name: Presence Hallway
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_hallway', 'on') }}
        entity_id:
          - input_boolean.presence_hallway_motion
          - input_boolean.presence_hallway_assistant
          - group.presence_hallway
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_hallway.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_bathroom:
        friendly_name: Presence Bathroom
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_bathroom', 'on') }}
        entity_id:
          - input_boolean.presence_bathroom_switch
          - input_boolean.presence_bathroom_door
          - input_boolean.presence_bathroom_shower
          - input_boolean.presence_bathroom_assistant
          - group.presence_bathroom
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_bathroom.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_laundry_room:
        friendly_name: Presence Laundry Room
        device_class: presence
        value_template: >-
          {{ is_state('group.presence_laundry_room', 'on') }}
        entity_id:
          - input_boolean.presence_laundry_room_motion
          - input_boolean.presence_laundry_room_assistant
          - group.presence_laundry_room
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_laundry_room.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_balcony:
        friendly_name: Presence Balcony
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_balcony', 'on') }}
        entity_id:
          - input_boolean.presence_balcony_door
          - input_boolean.presence_balcony_assistant
          - group.presence_balcony
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_balcony.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
      presence_closet:
        friendly_name: Presence Closet
        device_class: occupancy
        value_template: >-
          {{ is_state('group.presence_closet', 'on') }}
        entity_id:
          - input_boolean.presence_closet_motion
          - group.presence_closet
        attribute_templates:
          reason: >
            {% for entity in states.group.presence_closet.attributes.entity_id if is_state(entity, 'on') %}
            {%- if loop.first %}{% elif loop.last %} and {% else %}, {% endif -%}
            {{ states[entity.split('.')[0]][entity.split('.')[1]].name.split(' ') | last }}
            {%- endfor %}
